// `rsfusa template` — generate safety documentation templates.

use crate::config::load;
use crate::types::{EXIT_OK, EXIT_RUNTIME, EXIT_USAGE};
use std::io::Write;
use std::path::PathBuf;

pub fn run(args: &[String], stdout: &mut dyn Write, stderr: &mut dyn Write) -> i32 {
    let opts = match parse(args, stderr) {
        Some(o) => o,
        None => return EXIT_USAGE,
    };

    let project_root = opts.dir.unwrap_or_else(|| {
        std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."))
    });

    let out_dir = opts.out_dir.unwrap_or_else(|| {
        project_root.join("docs").join("safety").to_string_lossy().into_owned()
    });

    let cfg = load(&project_root.join(".fusa.json")).ok();
    let project = cfg.as_ref().map(|c| c.project.name.as_str()).unwrap_or("project");
    let standard = cfg.as_ref().map(|c| c.standard.as_str()).unwrap_or("generic");

    if let Err(e) = std::fs::create_dir_all(&out_dir) {
        writeln!(stderr, "rsfusa template: create {out_dir}: {e}").ok();
        return EXIT_RUNTIME;
    }

    let templates = match opts.kind.as_deref() {
        Some("safety-plan") => vec![("safety-plan.md", safety_plan_template(project, standard))],
        Some("test-plan") => vec![("test-plan.md", test_plan_template(project))],
        Some("review-checklist") => vec![("review-checklist.md", review_checklist_template())],
        Some("incident-report") => vec![("incident-report.md", incident_report_template())],
        _ => vec![
            ("safety-plan.md", safety_plan_template(project, standard)),
            ("test-plan.md", test_plan_template(project)),
            ("review-checklist.md", review_checklist_template()),
            ("incident-report.md", incident_report_template()),
        ],
    };

    let mut count = 0usize;
    for (name, content) in &templates {
        let path = PathBuf::from(&out_dir).join(name);
        if path.exists() && !opts.force {
            writeln!(stdout, "Skipping {name} (exists — use --force to overwrite)").ok();
            continue;
        }
        match std::fs::write(&path, content) {
            Ok(_) => {
                writeln!(stdout, "Created {}", path.display()).ok();
                count += 1;
            }
            Err(e) => {
                writeln!(stderr, "rsfusa template: write {}: {e}", path.display()).ok();
                return EXIT_RUNTIME;
            }
        }
    }
    writeln!(stdout, "Generated {count} template(s) in {out_dir}").ok();
    EXIT_OK
}

fn safety_plan_template(project: &str, standard: &str) -> String {
    format!(
        "# Safety Plan\n\n\
         **Project**: {project}  \n\
         **Standard**: {standard}  \n\
         **Version**: 0.1.0  \n\
         **Date**: TODO  \n\n\
         ## 1. Scope\n\nTODO: Define scope and safety goals.\n\n\
         ## 2. Safety Goals\n\n- SG-01: TODO\n\n\
         ## 3. Development Process\n\n\
         This project follows the rust-FuSa toolkit for safety assurance.\n\n\
         ## 4. Verification and Validation\n\n\
         - Static analysis: `rsfusa check`\n\
         - Test execution: `rsfusa verify`\n\
         - Requirements traceability: `rsfusa trace`\n\n\
         ## 5. Configuration Management\n\n\
         All source code is version-controlled with git. \
         SBOM generated by `rsfusa release`.\n\n\
         ## 6. Sign-off\n\n\
         | Role | Name | Date | Signature |\n\
         |------|------|------|-----------|\n\
         | Safety Manager | | | |\n\
         | Lead Developer | | | |\n"
    )
}

fn test_plan_template(project: &str) -> String {
    format!(
        "# Test Plan\n\n\
         **Project**: {project}  \n\
         **Version**: 0.1.0  \n\
         **Date**: TODO  \n\n\
         ## 1. Test Objectives\n\nTODO\n\n\
         ## 2. Test Scope\n\nTODO\n\n\
         ## 3. Test Strategy\n\n\
         - Unit tests: `cargo test`\n\
         - Coverage: `rsfusa coverage`\n\
         - Requirements traceability: annotate with `//fusa:test <REQ-ID>`\n\n\
         ## 4. Pass/Fail Criteria\n\n\
         - All unit tests pass\n\
         - Coverage ≥ required level for integrity class\n\
         - All requirements traced\n\n\
         ## 5. Test Cases\n\n\
         | ID | Requirement | Description | Expected Result | Status |\n\
         |----|-------------|-------------|-----------------|--------|\n\
         | TC-001 | REQ-TODO | TODO | TODO | |\n"
    )
}

fn review_checklist_template() -> String {
    "# Code Review Checklist\n\n\
     ## Safety\n\n\
     - [ ] No `unsafe` blocks without `//fusa:unsafe` justification\n\
     - [ ] No `.unwrap()` in library/safety code\n\
     - [ ] Error paths return `Result`; no silent failures\n\
     - [ ] Integer arithmetic uses checked variants where overflow is possible\n\
     - [ ] All public functions have `//fusa:req <ID>` annotations\n\n\
     ## Security\n\n\
     - [ ] No hardcoded credentials or secrets\n\
     - [ ] No SQL string concatenation\n\
     - [ ] Paths validated/canonicalized before use\n\
     - [ ] TLS certificate verification enabled\n\n\
     ## Code Quality\n\n\
     - [ ] Functions ≤ 60 lines\n\
     - [ ] No TODO/FIXME comments\n\
     - [ ] `rsfusa check` exits 0 with no new findings\n\
     - [ ] Test coverage maintained\n\n\
     ## Sign-off\n\n\
     Reviewer: _______________  Date: _______________\n".to_string()
}

fn incident_report_template() -> String {
    "# Incident Report\n\n\
     **Date**: TODO  \n\
     **Severity**: (critical/major/minor)  \n\
     **Phase**: (requirements/design/implementation/testing/operation)  \n\n\
     ## Summary\n\nTODO\n\n\
     ## Root Cause\n\nTODO\n\n\
     ## Impact\n\nTODO\n\n\
     ## Corrective Action\n\nTODO\n\n\
     ## Preventive Action\n\nTODO\n\n\
     ## Status\n\nOpen / Closed — Date: ___________\n".to_string()
}

struct Opts {
    dir: Option<PathBuf>,
    out_dir: Option<String>,
    kind: Option<String>,
    force: bool,
}

fn parse(args: &[String], stderr: &mut dyn Write) -> Option<Opts> {
    let mut opts = Opts { dir: None, out_dir: None, kind: None, force: false };
    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--force" => opts.force = true,
            flag @ ("--dir" | "--out-dir" | "--kind") => {
                if i + 1 >= args.len() {
                    writeln!(stderr, "rsfusa template: {flag} requires an argument").ok();
                    return None;
                }
                i += 1;
                match flag {
                    "--dir" => opts.dir = Some(PathBuf::from(args[i].clone())),
                    "--out-dir" => opts.out_dir = Some(args[i].clone()),
                    "--kind" => opts.kind = Some(args[i].clone()),
                    _ => {}
                }
            }
            other => {
                if let Some(v) = other.strip_prefix("--dir=") { opts.dir = Some(PathBuf::from(v)); }
                else if let Some(v) = other.strip_prefix("--out-dir=") { opts.out_dir = Some(v.to_string()); }
                else if let Some(v) = other.strip_prefix("--kind=") { opts.kind = Some(v.to_string()); }
                else if !other.starts_with("--") { opts.kind = Some(other.to_string()); }
                else {
                    writeln!(stderr, "rsfusa template: unknown flag: {other}").ok();
                    return None;
                }
            }
        }
        i += 1;
    }
    Some(opts)
}
